"""
Initial schema.

Revision ID: 0001
Revises:
Create Date: 2026-08-23 01:11:34.359657
"""

from __future__ import annotations

import alembic.op as op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Create the initial schema.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_findings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("audit_run_id", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_findings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_findings_audit_run_id"),
            ["audit_run_id"],
            unique=False,
        )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("at", sa.String(length=40), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("subject_type", sa.String(length=32), nullable=False),
        sa.Column("subject_id", sa.String(length=128), nullable=False),
        sa.Column("detail_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_at"), ["at"], unique=False)
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("goal", sa.Text(), nullable=True),
        sa.Column("capability_id", sa.String(length=128), nullable=True),
        sa.Column("vendor_id", sa.String(length=128), nullable=True),
        sa.Column("profile_id", sa.String(length=128), nullable=True),
        sa.Column("tenant", sa.String(length=64), nullable=True),
        sa.Column("bootstrap", sa.Boolean(), nullable=False),
        sa.Column("inputs_json", sa.Text(), nullable=False),
        sa.Column("result_json", sa.Text(), nullable=True),
        sa.Column("evidence_dir", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("started_at", sa.String(length=40), nullable=True),
        sa.Column("finished_at", sa.String(length=40), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_runs_capability_id"), ["capability_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_runs_status"), ["status"], unique=False
        )
    op.create_table(
        "secret_refs",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("backend", sa.String(length=16), nullable=False),
        sa.Column("locator", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("last_checked_at", sa.String(length=40), nullable=True),
        sa.Column("present", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "stability_records",
        sa.Column("capability_id", sa.String(length=128), nullable=False),
        sa.Column("runs", sa.Integer(), nullable=False),
        sa.Column("successes", sa.Integer(), nullable=False),
        sa.Column("last_run_at", sa.String(length=40), nullable=True),
        sa.Column("last_run_id", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("capability_id"),
    )
    op.create_table(
        "stability_samples",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("capability_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stability_samples", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stability_samples_capability_id"),
            ["capability_id"],
            unique=False,
        )
    op.create_table(
        "approvals",
        sa.Column("id", sa.String(length=96), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("step", sa.String(length=128), nullable=True),
        sa.Column("action_kind", sa.String(length=32), nullable=False),
        sa.Column("app", sa.String(length=128), nullable=True),
        sa.Column("details_json", sa.Text(), nullable=False),
        sa.Column("proposed_grants_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("decided_by", sa.String(length=64), nullable=True),
        sa.Column("remember", sa.String(length=16), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("raised_at", sa.String(length=40), nullable=False),
        sa.Column("decided_at", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_approvals_run_id"), ["run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_approvals_status"), ["status"], unique=False
        )
    op.create_table(
        "clarifications",
        sa.Column("id", sa.String(length=96), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("raised_at", sa.String(length=40), nullable=False),
        sa.Column("answered_at", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("clarifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_clarifications_run_id"), ["run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_clarifications_status"), ["status"], unique=False
        )
    op.create_table(
        "interventions",
        sa.Column("id", sa.String(length=96), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("page_title", sa.Text(), nullable=True),
        sa.Column("edge_id", sa.String(length=128), nullable=True),
        sa.Column("screenshot_file", sa.String(length=255), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("human_actions_json", sa.Text(), nullable=False),
        sa.Column("raised_at", sa.String(length=40), nullable=False),
        sa.Column("taken_at", sa.String(length=40), nullable=True),
        sa.Column("resolved_at", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("interventions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_interventions_run_id"), ["run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_interventions_state"), ["state"], unique=False
        )
    op.create_table(
        "run_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("at", sa.String(length=40), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("screenshot_file", sa.String(length=255), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "seq", name="uq_run_events_run_seq"),
    )
    with op.batch_alter_table("run_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_run_events_run_type", ["run_id", "type"], unique=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Drop the initial schema.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run_events", schema=None) as batch_op:
        batch_op.drop_index("ix_run_events_run_type")
    op.drop_table("run_events")
    with op.batch_alter_table("interventions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_interventions_state"))
        batch_op.drop_index(batch_op.f("ix_interventions_run_id"))
    op.drop_table("interventions")
    with op.batch_alter_table("clarifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_clarifications_status"))
        batch_op.drop_index(batch_op.f("ix_clarifications_run_id"))
    op.drop_table("clarifications")
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approvals_status"))
        batch_op.drop_index(batch_op.f("ix_approvals_run_id"))
    op.drop_table("approvals")
    with op.batch_alter_table("stability_samples", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stability_samples_capability_id"))
    op.drop_table("stability_samples")
    op.drop_table("stability_records")
    op.drop_table("secret_refs")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_status"))
        batch_op.drop_index(batch_op.f("ix_runs_capability_id"))
    op.drop_table("runs")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_at"))
    op.drop_table("audit_log")
    with op.batch_alter_table("audit_findings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_findings_audit_run_id"))
    op.drop_table("audit_findings")
    # ### end Alembic commands ###
